### ISSUE TITLE
Config Options?

### ISSUE THREAD

**Issue by livejamie** [panicsteve/cloud-to-butt#39]
Would be nice to have a blacklist or something, like if I didn't want it to replace soundcloud to soundbutt :)

**Comment by Long-Horse** [comment]
yeah I agree. maybe just no URLs

**Comment by panicsteve** [comment]
My original version of Cloud To Butt (the one in this repository) never replaces the individual word "cloud".  It must be preceded by the word "the" and a space.  However, there are forked versions of this project out in the world which do not have this restriction.  If you are using one of those, you should send feedback to the person who owns that project.
