### ISSUE TITLE
How can I improve it?

### ISSUE THREAD

**Issue by bensoy** [panicsteve/cloud-to-butt#48]
I want to use this extension to improve my surfing experience. I'm using my own protocol scheme but I give my example with "steam" What should I do to make it work like this:

Extension detects string in page: steam://loremipsum
Transforms it to a link like: <a href="steam://loremipsum"> steam://loremipsum </a> (loremipsum part is a variable, it should detect string from steam:// to next space character.

Is it possible? It reminds me how Skype Click to Call works but I don't have enough knowledge to do this kind of query & transform.

I would be very happy if you can help me or show me a way to do it. Thanks a lot!

**Comment by panicsteve** [comment]
I'm not sure exactly what you're asking... C2B operates via JavaScript directly on the DOM model of a webpage as constructed by the web browser.  It doesn't know anything about the underlying transport protocol (HTTP or anything else), or the URL.

**Comment by bensoy** [comment]
Just forget everything I said.

I want to replace `cloud1234` to `<a href="cloud1234">cloud1234</a>. 1234 is varies so I can't add a rule like this. How can I do that?

**Comment by panicsteve** [comment]
You would probably want to pattern match the string using a Regular Expression.

**Comment by bensoy** [comment]
Thank you, I will search for that!
