### ISSUE TITLE
URLs should NOT be CtB'd

### ISSUE THREAD

**Issue by Long-Horse** [panicsteve/cloud-to-butt#49]
push an update that DOESN'T TOUCH URLs http://soundbutt.com

I just edited a wiki with a ton of soundcloud links and now they're all broken.

**Comment by panicsteve** [comment]
My original version of Cloud To Butt (the one in this repository) never replaces the individual word "cloud".  It must be preceded by the word "the" and a space.  However, there are forked versions of this project out in the world which do not have this restriction.  If you are using one of those, you should send feedback to the person who owns that project.
