### ISSUE TITLE
Ignore <code> and <pre> blocks

### ISSUE THREAD

**Issue by dpkonofa** [panicsteve/cloud-to-butt#51]
I've had a few instances where I've pasted something from buttfront.net or buttflare.com.  If someone's not careful, it could backfire on them.  Love the extension, but it should ignore &lt;code> and &lt;pre> blocks.

**Comment by mattress** [comment]
+1

**Comment by panicsteve** [comment]
My extension only replaces the exact string "the cloud" with "my butt" -- it does not replace "cloud" with "butt", however, some of the extensions forked from mine do. Please follow up with the owner of the repository of the extension you're using.
