### ISSUE TITLE
Url schemes should be ignored in markdown

### ISSUE THREAD

**Issue by SchizoDuckie** [panicsteve/cloud-to-butt#52]
I noticed this little issue when working with github with my butt-to-butt extension enabled: pasted screenshots are replaced to butt.githubusercontent.com upon editing an issue.

Can we blacklist those somehow?

Example:
panicsteve

![image](https://cloud.githubusercontent.com/assets/111710/8717744/7869bd32-2b9e-11e5-84df-26f58fd730d1.png)

becomes 
![image](https://butt.githubusercontent.com/assets/111710/8717744/7869bd32-2b9e-11e5-84df-26f58fd730d1.png)

**Comment by panicsteve** [comment]
My extension only replaces the exact string "the cloud" with "my butt" (including the whitespace, so it can't match URLs) -- it does not replace the single word "cloud" with the single word "butt", HOWEVER!, some of the extensions forked from mine do. Please follow up with the owner of the repository of the extension you're using.

**Comment by SchizoDuckie** [comment]
Sorry, my bad! Thanks for your response :)
