### ISSUE TITLE
broke image link to cloudfront.net

### ISSUE THREAD

**Issue by metaphoricalstate** [panicsteve/cloud-to-butt#64]
the html was changed to

`<img src="//d37djvu3ytnwxt.buttfront.net/assets/courseware/v1/7dc1950019ebf9e1eb9dca6a706068ec/asset-v1:PennX+SD2x+2T2017+type@asset+block/1-1.PNG" style="width:850px;height:115px;">`

**Comment by panicsteve** [comment]
This extension does not replace "cloud", only "the cloud".  You are using a fork.  See README for more info.
