### ISSUE TITLE
add "serverless"

### ISSUE THREAD

**Issue by chpio** [panicsteve/cloud-to-butt#68]
"serverless" seems to be a new hype alias for "cloud"

please add "serverless" as alternative to "cloud"

**Comment by shtrom** [comment]
Can it be rewritten to `pants-less`?

> We are going all pants-less: we move everything to the butt.

**Comment by bexelbie** [comment]
I feel like buttless may be better.  @panicsteve interested in the expansion at all? I can send you a PR

**Comment by panicsteve** [comment]
I prefer forks for this sort of thing because I like cloud-to-butt best as a one joke pony. But with your own fork, the world is your oyster...
